name: Pull Request

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build:
    env:
      Configuration: Release

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core CLI
      uses: actions/setup-dotnet@v1.1.0

    - name: Build
      run: |
        dotnet publish --configuration ${{ env.Configuration }} src/restext.compiler.sln -p:Version=1.0.0 --version-suffix "build.${{ github.run_number }}" -f net48
        dotnet publish --configuration ${{ env.Configuration }} src/restext.compiler.sln -p:Version=1.0.0 --version-suffix "build.${{ github.run_number }}" -f net6.0
        dotnet pack    --configuration ${{ env.Configuration }} src/restext.compiler.sln -p:Version=1.0.0 --version-suffix "build.${{ github.run_number }}" -o dist --no-build
