name: Push Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    env:
      Configuration: Release

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        $Tag = "${{ github.ref }}" -replace '(refs/tags/)(.+)', '$2'
        $Version = $Tag -replace '((\d+)(\.\d+){1,3})(-.+|)', '$1'
        $InformationalVersion = "$Tag SHA-${{ github.SHA }}"
        $PackageVersion = $Tag
        echo "Version: $Tag"
        echo "Informational Version: $InformationalVersion"
        echo "Package Version: $PackageVersion"
        dotnet pack    --configuration ${{ env.Configuration }} src/restext.compiler.sln -p:AssemblyVersion=$Version -p:FileVersion=$Version -p:InformationalVersion=$InformationalVersion -p:PackageVersion=$Tag -o dist

    - name: Push
      run: |
        Get-ChildItem -Filter dist\*.nupkg | ForEach-Object {
            dotnet nuget push --api-key ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json $_
        }