name: Push Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        export
        export Tag=${github_ref/#refs\/tags\//}
        export Version=${Tag/%-*/}
        export InformationalVersion="$Tag+$github_sha"
        export PackageVersion=Tag
        echo "Version: $Version"
        echo "Informational Version: $InformationalVersion"
        echo "Package Version: $PackageVersion"
        dotnet pack --configuration release src/GitMirror.sln -o dist -p:AssemblyVersion=$Version -p:FileVersion=$Version -p:InformationalVersion=$InformationalVersion -p:PackageVersion=$Tag

    - name: Push
      run: |
        for f in dist\*.nupkg; do
          dotnet nuget push --api-key ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json dist/$f;
        done

