name: Push Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Build
    #   run: |
    #     export
    #     export Tag=${GITHUB_REF/#refs\/tags\//}
    #     export Version=${Tag/%-*/}
    #     export InformationalVersion="$Tag+$GITHUB_SHA"
    #     export PackageVersion=$Tag
    #     echo "Version: $Version"
    #     echo "Informational Version: $InformationalVersion"
    #     echo "Package Version: $PackageVersion"
    #     dotnet pack --configuration release src/restext.compiler.sln -o dist -p:AssemblyVersion=$Version -p:FileVersion=$Version -p:InformationalVersion=$InformationalVersion -p:PackageVersion=$Tag

    # - name: Push
    #   run: |
    #     for f in dist/*.nupkg; do
    #       dotnet nuget push --api-key ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json $f;
    #     done

    - name: Build
      run: |
        $Tag = "${{ github.ref }}" -replace '(refs/tags/)(.+)', '$2'
        $Version = $Tag -replace '((\d+)(\.\d+){1,3})(-.+|)', '$1'
        $InformationalVersion = "$Tag SHA-${{ github.SHA }}"
        $PackageVersion = $Tag
        echo "Version: $Tag"
        echo "Informational Version: $InformationalVersion"
        echo "Package Version: $PackageVersion"
        dotnet pack --configuration release src/restext.compiler.sln -o dist -p:AssemblyVersion=$Version -p:FileVersion=$Version -p:InformationalVersion=$InformationalVersion -p:PackageVersion=$Tag

    - name: Push
      run: |
        Get-ChildItem -Filter dist\*.nupkg | dotnet nuget push --api-key ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json  $_.Name